org: glothos
app: homilia-bot-handler
service: homilia-bot-handler
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    TABLE_NAME:
      Ref: AudioFileReference
    TOPIC_ARN:
      Ref: CrossFunctionCall
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
          Resource:
            - 'Fn::GetAtt': [AudioFileReference, Arn]
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - !Ref CrossFunctionCall

functions:
  transcoder:
    handler: src/functions/transcoder.handler
    dependsOn: CrossFunctionCall
    events:
      - sns:
          arn: !Ref CrossFunctionCall
          topicName: cross-function-call
    # layers:
    #   - { Ref: FfmpegLambdaLayer }
  webhook:
    handler: src/functions/webhook.handler
    events:
      - httpApi:
          path: /webhook
          method: post
layers:
  ffmpeg:
    path: layer

resources:
  Resources:
    CrossFunctionCall:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: cross-function-call
    AudioFileReference:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AudioFileReference
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
